// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NghienCuuKhoaHoc.Data;

#nullable disable

namespace NghienCuuKhoaHoc.Data.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "caea4300-91d6-42f8-9dd7-80f8c9f6f88f",
                            ConcurrencyStamp = "be3bd974-69e0-4b35-9c12-69c8f1b88e1f",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "69bd714f-9576-45ba-b5b7-f00649be00de",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b56a45c3-6bd0-4329-a50f-ce5e07c6c369",
                            Email = "Ngohung3437@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Ngohung3437@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEApay+THB20dUeNftP97CkVM+ocSsB7sDhhKdP1AYLgtKf3Wn0t3V7jHV6ekLoe8mw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "72bd714f-4856-45ba-b5b7-f00649be00de",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "de6e450d-232f-4a61-b41d-eb7dd5031d29",
                            Email = "Ngohung3437@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Ngohung3437@gmail.com",
                            NormalizedUserName = "admin1",
                            PasswordHash = "AQAAAAEAACcQAAAAEMnSjNkVA9t5SsGJFHeqsRAwe4yg+zq6bwNYUZGQjsOP3BfuY9XYkQlmgPXb5ScCPQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin1"
                        },
                        new
                        {
                            Id = "72bd714f-7812-45ba-b5b7-f00649be00de",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c9b04d0-b811-4629-81d7-e3a579977ae8",
                            Email = "Ngohung3437@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Ngohung3437@gmail.com",
                            NormalizedUserName = "admin2",
                            PasswordHash = "AQAAAAEAACcQAAAAECOiD0y7EEGlGdke6IgWHESUZeIoOrDOIEi7LomNOa9Qzb5QGqcXynT2T6IkS99OVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "72bd714f-7812-45ba-b5b7-f00649be00de",
                            RoleId = "caea4300-91d6-42f8-9dd7-80f8c9f6f88f"
                        },
                        new
                        {
                            UserId = "72bd714f-4856-45ba-b5b7-f00649be00de",
                            RoleId = "caea4300-91d6-42f8-9dd7-80f8c9f6f88f"
                        },
                        new
                        {
                            UserId = "69bd714f-9576-45ba-b5b7-f00649be00de",
                            RoleId = "caea4300-91d6-42f8-9dd7-80f8c9f6f88f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.CouncilMember", b =>
                {
                    b.Property<string>("ResearchId")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("MemberId")
                        .HasColumnType("varchar(12)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("ResearchId", "MemberId");

                    b.HasIndex("MemberId");

                    b.HasIndex("Position");

                    b.ToTable("CouncilMembers");

                    b.HasData(
                        new
                        {
                            ResearchId = "211111116666",
                            MemberId = "111111111111",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "211111116666",
                            MemberId = "111111133333",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "211111116666",
                            MemberId = "111111166666",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "211111116666",
                            MemberId = "111111155555",
                            Position = 3
                        },
                        new
                        {
                            ResearchId = "21111113333",
                            MemberId = "111111111111",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "21111113333",
                            MemberId = "111111133333",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "21111113333",
                            MemberId = "111111166666",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "21111113333",
                            MemberId = "111111155555",
                            Position = 3
                        },
                        new
                        {
                            ResearchId = "21111112222",
                            MemberId = "111111111111",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "21111112222",
                            MemberId = "111111133333",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "21111112222",
                            MemberId = "111111166666",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "21111112222",
                            MemberId = "111111155555",
                            Position = 3
                        },
                        new
                        {
                            ResearchId = "21111111111",
                            MemberId = "111111111111",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "21111111111",
                            MemberId = "111111133333",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "21111111111",
                            MemberId = "111111144444",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "21111111111",
                            MemberId = "111111177777",
                            Position = 3
                        },
                        new
                        {
                            ResearchId = "111111119999",
                            MemberId = "111111122222",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "111111119999",
                            MemberId = "111111133333",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "111111119999",
                            MemberId = "111111144444",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "111111119999",
                            MemberId = "111111155555",
                            Position = 3
                        },
                        new
                        {
                            ResearchId = "111111118888",
                            MemberId = "411111122222",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "111111118888",
                            MemberId = "211111111111",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "111111118888",
                            MemberId = "211111122222",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "111111118888",
                            MemberId = "211111133333",
                            Position = 3
                        },
                        new
                        {
                            ResearchId = "111111117777",
                            MemberId = "411111122222",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "111111117777",
                            MemberId = "211111111111",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "111111117777",
                            MemberId = "211111122222",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "111111117777",
                            MemberId = "211111133333",
                            Position = 3
                        },
                        new
                        {
                            ResearchId = "111111116666",
                            MemberId = "111111155555",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "111111116666",
                            MemberId = "111111166666",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "111111116666",
                            MemberId = "111111177777",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "111111116666",
                            MemberId = "111111133333",
                            Position = 3
                        },
                        new
                        {
                            ResearchId = "111111115555",
                            MemberId = "311111155555",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "111111115555",
                            MemberId = "311111166666",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "111111115555",
                            MemberId = "311111144444",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "111111115555",
                            MemberId = "311111133333",
                            Position = 3
                        },
                        new
                        {
                            ResearchId = "111111114444",
                            MemberId = "311111111111",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "111111114444",
                            MemberId = "311111122222",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "111111114444",
                            MemberId = "311111144444",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "111111114444",
                            MemberId = "311111133333",
                            Position = 3
                        },
                        new
                        {
                            ResearchId = "111111113333",
                            MemberId = "411111111111",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "111111113333",
                            MemberId = "411111122222",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "111111113333",
                            MemberId = "211111111111",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "111111113333",
                            MemberId = "211111133333",
                            Position = 3
                        },
                        new
                        {
                            ResearchId = "111111111111",
                            MemberId = "411111111111",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "111111111111",
                            MemberId = "411111122222",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "111111111111",
                            MemberId = "211111122222",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "111111111111",
                            MemberId = "211111133333",
                            Position = 3
                        },
                        new
                        {
                            ResearchId = "111111112222",
                            MemberId = "111111155555",
                            Position = 0
                        },
                        new
                        {
                            ResearchId = "111111112222",
                            MemberId = "111111166666",
                            Position = 1
                        },
                        new
                        {
                            ResearchId = "111111112222",
                            MemberId = "111111177777",
                            Position = 2
                        },
                        new
                        {
                            ResearchId = "111111112222",
                            MemberId = "111111111111",
                            Position = 3
                        });
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = "CNTT",
                            CreatedDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Công Nghệ Thông Tin"
                        },
                        new
                        {
                            Id = "CNHH",
                            CreatedDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Công Nghệ Hóa Học"
                        },
                        new
                        {
                            Id = "CNOT",
                            CreatedDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Công Nghệ Ô Tô"
                        },
                        new
                        {
                            Id = "CNCK",
                            CreatedDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cơ Khí"
                        });
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Công nghệ Thông tin"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Kỹ thuật - Cơ khí"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Công nghệ hóa học"
                        });
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.Literacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Literacies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Cử nhân"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Thạc sĩ"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Tiến sĩ"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Phó giáo sư"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Giáo sư"
                        });
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.Personal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birth")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Literacy")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Id");

                    b.ToTable("Personals");

                    b.HasData(
                        new
                        {
                            Id = "311111111111",
                            Avatar = "/plugins/images/users/025080010611.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNTT",
                            Email = "Nguyenquockhanh@vui.com",
                            Gender = true,
                            Literacy = "Thạc sĩ",
                            Name = "Nguyễn Quốc Khánh",
                            PhoneNumber = "0965875697",
                            Position = "Trưởng bộ môn"
                        },
                        new
                        {
                            Id = "311111122222",
                            Avatar = "/plugins/images/users/025080002921.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNTT",
                            Email = "Docaominh@vui.com",
                            Gender = true,
                            Literacy = "Thạc sĩ",
                            Name = "Đỗ Cao Minh",
                            PhoneNumber = "0364859669",
                            Position = "Phó trưởng khoa"
                        },
                        new
                        {
                            Id = "311111133333",
                            Avatar = "",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNTT",
                            Email = "Hathithuhien@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Hà Thị Thu Hiền",
                            PhoneNumber = "0585469852",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "311111144444",
                            Avatar = "/plugins/images/users/038075028517.JPG",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNTT",
                            Email = "Levandiep@vui.com",
                            Gender = true,
                            Literacy = "Thạc sĩ",
                            Name = "Lê Văn Điệp",
                            PhoneNumber = "0856325855",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "311111155555",
                            Avatar = "/plugins/images/users/015176004351.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNTT",
                            Email = "Tranthihiep@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Trần Thị Hiệp",
                            PhoneNumber = "0364859669",
                            Position = "Trưởng khoa"
                        },
                        new
                        {
                            Id = "311111166666",
                            Avatar = "/plugins/images/users/131302862.JPG",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNTT",
                            Email = "Dothihong@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Đỗ Thị Hồng",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "311111177777",
                            Avatar = "/plugins/images/users/063397395.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNTT",
                            Email = "Nguyenngocanh@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Nguyễn Ngọc Ánh",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "311111199999",
                            Avatar = "/plugins/images/users/131459038.JPG",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNTT",
                            Email = "Nguyenthuhuong@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Nguyễn Thu Hường",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "311111211111",
                            Avatar = "/plugins/images/users/025088015041.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNTT",
                            Email = "Daominhsang@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Đào Minh Sang",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "311111222222",
                            Avatar = "/plugins/images/users/025188012664.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNTT",
                            Email = "Vuthuthao@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Vũ Thu Thảo",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "311111233333",
                            Avatar = "/plugins/images/users/034184019053.JPG",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNTT",
                            Email = "Phamthuthuy@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Phạm Thu Thủy",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "111111111111",
                            Avatar = "/plugins/images/users/agent.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNHH",
                            Email = "Nguyenmanhtien@vui.com",
                            Gender = true,
                            Literacy = "Thạc sĩ",
                            Name = "Nguyễn Mạnh Tiến",
                            PhoneNumber = "0364859669",
                            Position = "Trưởng khoa"
                        },
                        new
                        {
                            Id = "111111122222",
                            Avatar = "/plugins/images/users/agent.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNHH",
                            Email = "Nguyenvanan@vui.com",
                            Gender = true,
                            Literacy = "Thạc sĩ",
                            Name = "Nguyễn Văn An",
                            PhoneNumber = "0364859669",
                            Position = "Trưởng khoa"
                        },
                        new
                        {
                            Id = "111111133333",
                            Avatar = "/plugins/images/users/6.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNHH",
                            Email = "Buidinhnhi@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Bùi Đinh Nhi",
                            PhoneNumber = "0364859669",
                            Position = "Trưởng bộ môn"
                        },
                        new
                        {
                            Id = "111111144444",
                            Avatar = "/plugins/images/users/8.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNHH",
                            Email = "Lethiminhhang@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Lê Thị Minh Hằng",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "111111155555",
                            Avatar = "/plugins/images/users/hritik.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNHH",
                            Email = "Hoangthikimvan@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Hoàng Thị Kim Vân",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "111111166666",
                            Avatar = "/plugins/images/users/23.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNHH",
                            Email = "Damthuynga@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Đàm Thị Thùy Nga",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "111111177777",
                            Avatar = "/plugins/images/users/54.jfif",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNHH",
                            Email = "Ngohongnghia@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Ngô Hồng Nghĩa",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "211111111111",
                            Avatar = "/plugins/images/users/3.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNOT",
                            Email = "Lequangvinh@vui.com",
                            Gender = true,
                            Literacy = "Thạc sĩ",
                            Name = "Lê Quang Vinh",
                            PhoneNumber = "0364859669",
                            Position = "Trưởng bộ môn"
                        },
                        new
                        {
                            Id = "211111122222",
                            Avatar = "/plugins/images/users/3f086fe2-25fc-47e4-a861-92105f58f973.jfif",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNOT",
                            Email = "Nguyenthiquynh@vui.com",
                            Gender = false,
                            Literacy = "Thạc sĩ",
                            Name = "Nguyễn Thị Quỳnh",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "211111133333",
                            Avatar = "/plugins/images/users/d4.jpg",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNOT",
                            Email = "Tranvantan@vui.com",
                            Gender = true,
                            Literacy = "Thạc sĩ",
                            Name = "Trần Văn Tân",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "411111111111",
                            Avatar = "/plugins/images/users/3.png",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNCK",
                            Email = "Vuquochien@vui.com",
                            Gender = true,
                            Literacy = "Thạc sĩ",
                            Name = "Vũ Quốc Hiến",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        },
                        new
                        {
                            Id = "411111122222",
                            Avatar = "/plugins/images/users/3.png",
                            Birth = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "CNCK",
                            Email = "Phamngocthanh@vui.com",
                            Gender = true,
                            Literacy = "Thạc sĩ",
                            Name = "Phạm Ngọc Thành",
                            PhoneNumber = "0364859669",
                            Position = "Giảng viên"
                        });
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Trưởng khoa"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Phó trưởng khoa"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Giảng viên"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Trưởng bộ môn"
                        });
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.Research", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime?>("DateExpired")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Expense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("InstructorId")
                        .HasColumnType("varchar(12)");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("DateExpired");

                    b.HasIndex("DateStarted");

                    b.HasIndex("Expense");

                    b.HasIndex("Field");

                    b.HasIndex("InstructorId");

                    b.HasIndex("Status");

                    b.ToTable("Researches");

                    b.HasData(
                        new
                        {
                            Id = "211111117777",
                            DateExpired = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 18941000m,
                            Field = "Kỹ thuật - Cơ khí",
                            InstructorId = "411111122222",
                            Status = 0,
                            Subject = "Thiết kế chế tạo ABC XYZ tiết kiệm nhiên liệu ECORUN"
                        },
                        new
                        {
                            Id = "211111116666",
                            DateExpired = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 10080000m,
                            Field = "Công nghệ hóa học",
                            InstructorId = "111111166666",
                            Status = 1,
                            Subject = "Sản xuất ABC XYZ theo phương pháp truyền thống"
                        },
                        new
                        {
                            Id = "21111115555",
                            DateExpired = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 5470000m,
                            Field = "Công nghệ hóa học",
                            InstructorId = "111111177777",
                            Status = 0,
                            Subject = "Nghiên cứu một số phương pháp ABC XYZ"
                        },
                        new
                        {
                            Id = "21111114444",
                            DateExpired = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 2570000m,
                            Field = "Công nghệ hóa học",
                            InstructorId = "311111155555",
                            Status = 0,
                            Subject = "Xây dựng phần mềm tra ABZ XYZ, chứng chỉ của Trường Đại học Công nghiệp Việt Trì"
                        },
                        new
                        {
                            Id = "21111113333",
                            DateExpired = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 2570000m,
                            Field = "Công nghệ hóa học",
                            InstructorId = "311111155555",
                            Status = 1,
                            Subject = "Xây dựng Trang web ABZ XYZ của Trường Đại học Công nghiệp Việt Trì"
                        },
                        new
                        {
                            Id = "21111112222",
                            DateExpired = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 2570000m,
                            Field = "Công nghệ hóa học",
                            InstructorId = "311111155555",
                            Status = 2,
                            Subject = "Xây dựng phần mềm tra cứu văn bằng, chứng chỉ của Trường Đại học Công nghiệp Việt Trì"
                        },
                        new
                        {
                            Id = "21111111111",
                            DateExpired = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 5470000m,
                            Field = "Công nghệ hóa học",
                            InstructorId = "111111177777",
                            Status = 2,
                            Subject = "Nghiên cứu một số phương pháp thu hồi silic đioxit từ vỏ trấu"
                        },
                        new
                        {
                            Id = "111111119999",
                            DateExpired = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 10080000m,
                            Field = "Công nghệ hóa học",
                            InstructorId = "111111166666",
                            Status = 2,
                            Subject = "Sản xuất nước giải khát chanh leo nha đam lên men theo phương pháp truyền thống"
                        },
                        new
                        {
                            Id = "111111118888",
                            DateExpired = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 18941000m,
                            Field = "Kỹ thuật - Cơ khí",
                            InstructorId = "411111122222",
                            Status = 2,
                            Subject = "Thiết kế chế tạo xe tiết kiệm nhiên liệu ECORUN"
                        },
                        new
                        {
                            Id = "111111117777",
                            DateExpired = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 19950000m,
                            Field = "Kỹ thuật - Cơ khí",
                            InstructorId = "411111111111",
                            Status = 2,
                            Subject = "Nghiên cứu thiết kế, chế tạo mô hình tập lái xe ô tô ảo"
                        },
                        new
                        {
                            Id = "111111116666",
                            DateExpired = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2019, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 9300000m,
                            Field = "Công nghệ hóa học",
                            InstructorId = "111111155555",
                            Status = 2,
                            Subject = "Nghiên cứu hoàn thiện quy trình tách chiết và xác định thành phần hóa học của tinh dầu hoa ngọc lan trồng ở Tỉnh Phú Thọ, ứng dụng sản xuất thử nghiệm nước lau sàn hương ngọc lan"
                        },
                        new
                        {
                            Id = "111111115555",
                            DateExpired = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2019, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 200000m,
                            Field = "Công nghệ Thông tin",
                            InstructorId = "311111166666",
                            Status = 2,
                            Subject = "Xây dựng phần mềm quản lý ký túc xá Trường Đại học Công nghiệp Việt Trì"
                        },
                        new
                        {
                            Id = "111111114444",
                            DateExpired = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2019, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 200000m,
                            Field = "Công nghệ Thông tin",
                            InstructorId = "311111155555",
                            Status = 2,
                            Subject = "Xây dựng hệ thống VoIP cho Trường Đại học Công nghiệp Việt Trì và nghiên cứu giải pháp bảo mật cho dịch vụ"
                        },
                        new
                        {
                            Id = "111111113333",
                            DateExpired = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2019, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 37500000m,
                            Field = "Kỹ thuật - Cơ khí",
                            InstructorId = "411111111111",
                            Status = 2,
                            Subject = "Nghiên cứu xây dựng phòng thực hành mô hình động cơ ô tô phục vụ công tác giảng dạy và nghiên cứu khoa học của Trường Đại học Công nghiệp Việt Trì"
                        },
                        new
                        {
                            Id = "111111112222",
                            DateExpired = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2019, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 14700000m,
                            Field = "Công nghệ hóa học",
                            InstructorId = "111111133333",
                            Status = 2,
                            Subject = "Nghiên cứu chế tạo chế phẩm sinh học Bateriocin giúp tăng cường bảo quản rau củ quả"
                        },
                        new
                        {
                            Id = "111111111111",
                            DateExpired = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2019, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Expense = 4081000m,
                            Field = "Kỹ thuật - Cơ khí",
                            InstructorId = "211111111111",
                            Status = 2,
                            Subject = "Nghiên cứu chế tạo máy thu gom rác sinh hoạt"
                        });
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.ResearchAcceptance", b =>
                {
                    b.Property<string>("ResearchId")
                        .HasColumnType("varchar(12)");

                    b.Property<int?>("Acceptance")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.HasKey("ResearchId");

                    b.HasIndex("Acceptance");

                    b.HasIndex("Rating");

                    b.HasIndex("ResearchId")
                        .IsUnique();

                    b.HasIndex("Score");

                    b.ToTable("ResearchAcceptances");

                    b.HasData(
                        new
                        {
                            ResearchId = "111111111111",
                            Acceptance = 0,
                            Rating = 1,
                            Score = 7.7000000000000002
                        },
                        new
                        {
                            ResearchId = "111111112222",
                            Acceptance = 0,
                            Rating = 1,
                            Score = 8.6999999999999993
                        },
                        new
                        {
                            ResearchId = "111111113333",
                            Acceptance = 0,
                            Rating = 0,
                            Score = 9.0
                        },
                        new
                        {
                            ResearchId = "111111114444",
                            Acceptance = 0,
                            Rating = 0,
                            Score = 9.0
                        },
                        new
                        {
                            ResearchId = "111111115555",
                            Acceptance = 0,
                            Rating = 0,
                            Score = 9.0
                        },
                        new
                        {
                            ResearchId = "111111116666",
                            Acceptance = 0,
                            Rating = 2,
                            Score = 6.9000000000000004
                        },
                        new
                        {
                            ResearchId = "111111117777",
                            Acceptance = 0,
                            Rating = 2,
                            Score = 6.9000000000000004
                        },
                        new
                        {
                            ResearchId = "111111118888",
                            Acceptance = 0,
                            Rating = 1,
                            Score = 6.9000000000000004
                        },
                        new
                        {
                            ResearchId = "111111119999",
                            Acceptance = 0,
                            Rating = 1,
                            Score = 7.9000000000000004
                        },
                        new
                        {
                            ResearchId = "21111111111",
                            Acceptance = 0,
                            Rating = 1,
                            Score = 7.9000000000000004
                        },
                        new
                        {
                            ResearchId = "21111112222",
                            Acceptance = 0,
                            Rating = 1,
                            Score = 7.9000000000000004
                        });
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.ResearchFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("File")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearchId")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("ResearchId");

                    b.ToTable("ResearchFiles");

                    b.HasData(
                        new
                        {
                            Id = "21111112222x94d8b0ea05858fbf36c",
                            File = "/files/21111112222/811e5df4-311a-47b9-afd8-dc8a4b287e25.docx",
                            FileExtend = "docx",
                            Name = "word_Do_an-VuHuuKhanh_IN.docx",
                            ResearchId = "21111112222"
                        },
                        new
                        {
                            Id = "21111112222a1mlsk41a74ba06279e8",
                            File = "/files/21111112222/8afc584f-e895-46ba-8e8b-999c637c87b9.pdf",
                            FileExtend = "pdf",
                            Name = "quyet dinh 1063-31.12.19.pdf",
                            ResearchId = "21111112222"
                        },
                        new
                        {
                            Id = "21111112222a87456ea40d512f27ce0",
                            File = "/files/21111112222/bcd301cf-5155-4a74-9a70-64077786c4a8.png",
                            FileExtend = "png",
                            Name = "#ireland #flower #flowers #girl #tumblr #ireland #tumblrgirl #travel #mexican #blogger (1).png",
                            ResearchId = "21111112222"
                        },
                        new
                        {
                            Id = "21111111111x94d8b0ea05858fbf36c",
                            File = "/files/21111111111/811e5df4-311a-47b9-afd8-dc8a4b287e25.docx",
                            FileExtend = "docx",
                            Name = "word_Do_an-VuHuuKhanh_IN.docx",
                            ResearchId = "21111111111"
                        },
                        new
                        {
                            Id = "21111111111a1mlsk41a74ba06279e8",
                            File = "/files/21111111111/8afc584f-e895-46ba-8e8b-999c637c87b9.pdf",
                            FileExtend = "pdf",
                            Name = "quyet dinh 1063-31.12.19.pdf",
                            ResearchId = "21111111111"
                        },
                        new
                        {
                            Id = "21111111111a87456ea40d512f27ce0",
                            File = "/files/21111111111/bcd301cf-5155-4a74-9a70-64077786c4a8.png",
                            FileExtend = "png",
                            Name = "#ireland #flower #flowers #girl #tumblr #ireland #tumblrgirl #travel #mexican #blogger (1).png",
                            ResearchId = "21111111111"
                        },
                        new
                        {
                            Id = "111111119999x94d8b0ea05858fbf36c",
                            File = "/files/111111119999/811e5df4-311a-47b9-afd8-dc8a4b287e25.docx",
                            FileExtend = "docx",
                            Name = "word_Do_an-VuHuuKhanh_IN.docx",
                            ResearchId = "111111119999"
                        },
                        new
                        {
                            Id = "111111119999a1mlsk41a74ba06279e8",
                            File = "/files/111111119999/8afc584f-e895-46ba-8e8b-999c637c87b9.pdf",
                            FileExtend = "pdf",
                            Name = "quyet dinh 1063-31.12.19.pdf",
                            ResearchId = "111111119999"
                        },
                        new
                        {
                            Id = "111111119999a87456ea40d512f27ce0",
                            File = "/files/111111119999/bcd301cf-5155-4a74-9a70-64077786c4a8.png",
                            FileExtend = "png",
                            Name = "#ireland #flower #flowers #girl #tumblr #ireland #tumblrgirl #travel #mexican #blogger (1).png",
                            ResearchId = "111111119999"
                        },
                        new
                        {
                            Id = "111111118888x94d8b0ea05858fbf36c",
                            File = "/files/111111118888/811e5df4-311a-47b9-afd8-dc8a4b287e25.docx",
                            FileExtend = "docx",
                            Name = "word_Do_an-VuHuuKhanh_IN.docx",
                            ResearchId = "111111118888"
                        },
                        new
                        {
                            Id = "111111118888a1mlsk41a74ba06279e8",
                            File = "/files/111111118888/8afc584f-e895-46ba-8e8b-999c637c87b9.pdf",
                            FileExtend = "pdf",
                            Name = "quyet dinh 1063-31.12.19.pdf",
                            ResearchId = "111111118888"
                        },
                        new
                        {
                            Id = "111111118888a87456ea40d512f27ce0",
                            File = "/files/111111118888/bcd301cf-5155-4a74-9a70-64077786c4a8.png",
                            FileExtend = "png",
                            Name = "#ireland #flower #flowers #girl #tumblr #ireland #tumblrgirl #travel #mexican #blogger (1).png",
                            ResearchId = "111111118888"
                        },
                        new
                        {
                            Id = "111111117777x94d8b0ea05858fbf36c",
                            File = "/files/111111117777/811e5df4-311a-47b9-afd8-dc8a4b287e25.docx",
                            FileExtend = "docx",
                            Name = "word_Do_an-VuHuuKhanh_IN.docx",
                            ResearchId = "111111117777"
                        },
                        new
                        {
                            Id = "111111117777a1mlsk41a74ba06279e8",
                            File = "/files/111111117777/8afc584f-e895-46ba-8e8b-999c637c87b9.pdf",
                            FileExtend = "pdf",
                            Name = "quyet dinh 1063-31.12.19.pdf",
                            ResearchId = "111111117777"
                        },
                        new
                        {
                            Id = "111111117777a87456ea40d512f27ce0",
                            File = "/files/111111117777/bcd301cf-5155-4a74-9a70-64077786c4a8.png",
                            FileExtend = "png",
                            Name = "#ireland #flower #flowers #girl #tumblr #ireland #tumblrgirl #travel #mexican #blogger (1).png",
                            ResearchId = "111111117777"
                        },
                        new
                        {
                            Id = "111111116666x94d8b0ea05858fbf36c",
                            File = "/files/111111116666/811e5df4-311a-47b9-afd8-dc8a4b287e25.docx",
                            FileExtend = "docx",
                            Name = "word_Do_an-VuHuuKhanh_IN.docx",
                            ResearchId = "111111116666"
                        },
                        new
                        {
                            Id = "111111116666a1mlsk41a74ba06279e8",
                            File = "/files/111111116666/8afc584f-e895-46ba-8e8b-999c637c87b9.pdf",
                            FileExtend = "pdf",
                            Name = "quyet dinh 1063-31.12.19.pdf",
                            ResearchId = "111111116666"
                        },
                        new
                        {
                            Id = "111111116666a87456ea40d512f27ce0",
                            File = "/files/111111116666/bcd301cf-5155-4a74-9a70-64077786c4a8.png",
                            FileExtend = "png",
                            Name = "#ireland #flower #flowers #girl #tumblr #ireland #tumblrgirl #travel #mexican #blogger (1).png",
                            ResearchId = "111111116666"
                        },
                        new
                        {
                            Id = "111111115555x94d8b0ea05858fbf36c",
                            File = "/files/111111115555/811e5df4-311a-47b9-afd8-dc8a4b287e25.docx",
                            FileExtend = "docx",
                            Name = "word_Do_an-VuHuuKhanh_IN.docx",
                            ResearchId = "111111115555"
                        },
                        new
                        {
                            Id = "111111115555a1mlsk41a74ba06279e8",
                            File = "/files/111111115555/8afc584f-e895-46ba-8e8b-999c637c87b9.pdf",
                            FileExtend = "pdf",
                            Name = "quyet dinh 1063-31.12.19.pdf",
                            ResearchId = "111111115555"
                        },
                        new
                        {
                            Id = "111111115555a87456ea40d512f27ce0",
                            File = "/files/111111115555/bcd301cf-5155-4a74-9a70-64077786c4a8.png",
                            FileExtend = "png",
                            Name = "#ireland #flower #flowers #girl #tumblr #ireland #tumblrgirl #travel #mexican #blogger (1).png",
                            ResearchId = "111111115555"
                        },
                        new
                        {
                            Id = "111111114444x94d8b0ea05858fbf36c",
                            File = "/files/111111114444/811e5df4-311a-47b9-afd8-dc8a4b287e25.docx",
                            FileExtend = "docx",
                            Name = "word_Do_an-VuHuuKhanh_IN.docx",
                            ResearchId = "111111114444"
                        },
                        new
                        {
                            Id = "111111114444a1mlsk41a74ba06279e8",
                            File = "/files/111111114444/8afc584f-e895-46ba-8e8b-999c637c87b9.pdf",
                            FileExtend = "pdf",
                            Name = "quyet dinh 1063-31.12.19.pdf",
                            ResearchId = "111111114444"
                        },
                        new
                        {
                            Id = "111111114444a87456ea40d512f27ce0",
                            File = "/files/111111114444/bcd301cf-5155-4a74-9a70-64077786c4a8.png",
                            FileExtend = "png",
                            Name = "#ireland #flower #flowers #girl #tumblr #ireland #tumblrgirl #travel #mexican #blogger (1).png",
                            ResearchId = "111111114444"
                        },
                        new
                        {
                            Id = "111111113333x94d8b0ea05858fbf36c",
                            File = "/files/111111113333/811e5df4-311a-47b9-afd8-dc8a4b287e25.docx",
                            FileExtend = "docx",
                            Name = "word_Do_an-VuHuuKhanh_IN.docx",
                            ResearchId = "111111113333"
                        },
                        new
                        {
                            Id = "111111113333a1mlsk41a74ba06279e8",
                            File = "/files/111111113333/8afc584f-e895-46ba-8e8b-999c637c87b9.pdf",
                            FileExtend = "pdf",
                            Name = "quyet dinh 1063-31.12.19.pdf",
                            ResearchId = "111111113333"
                        },
                        new
                        {
                            Id = "111111113333a87456ea40d512f27ce0",
                            File = "/files/111111113333/bcd301cf-5155-4a74-9a70-64077786c4a8.png",
                            FileExtend = "png",
                            Name = "#ireland #flower #flowers #girl #tumblr #ireland #tumblrgirl #travel #mexican #blogger (1).png",
                            ResearchId = "111111113333"
                        },
                        new
                        {
                            Id = "24e78948940a494d8b0ea05858fbf36c",
                            File = "/files/111111112222/811e5df4-311a-47b9-afd8-dc8a4b287e25.docx",
                            FileExtend = "docx",
                            Name = "word_Do_an-VuHuuKhanh_IN.docx",
                            ResearchId = "111111112222"
                        },
                        new
                        {
                            Id = "5a7719d66d8a41mlsk41a74ba06279e8",
                            File = "/files/111111112222/8afc584f-e895-46ba-8e8b-999c637c87b9.pdf",
                            FileExtend = "pdf",
                            Name = "quyet dinh 1063-31.12.19.pdf",
                            ResearchId = "111111112222"
                        },
                        new
                        {
                            Id = "8474ba31c552487456ea40d512f27ce0",
                            File = "/files/111111112222/bcd301cf-5155-4a74-9a70-64077786c4a8.png",
                            FileExtend = "png",
                            Name = "#ireland #flower #flowers #girl #tumblr #ireland #tumblrgirl #travel #mexican #blogger (1).png",
                            ResearchId = "111111112222"
                        },
                        new
                        {
                            Id = "24ee7418940a494d8b0ea05858fbf36c",
                            File = "/files/111111111111/811e5df4-311a-47b9-afd8-dc8a4b287e25.docx",
                            FileExtend = "docx",
                            Name = "word_Do_an-VuHuuKhanh_IN.docx",
                            ResearchId = "111111111111"
                        },
                        new
                        {
                            Id = "5a7719d66d8a41c4a241a74ba06279e8",
                            File = "/files/111111111111/8afc584f-e895-46ba-8e8b-999c637c87b9.pdf",
                            FileExtend = "pdf",
                            Name = "quyet dinh 1063-31.12.19.pdf",
                            ResearchId = "111111111111"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.CouncilMember", b =>
                {
                    b.HasOne("NghienCuuKhoaHoc.Data.Models.Personal", "Personal")
                        .WithMany("CouncilMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NghienCuuKhoaHoc.Data.Models.Research", "Research")
                        .WithMany("CouncilMembers")
                        .HasForeignKey("ResearchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("Research");
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.Personal", b =>
                {
                    b.HasOne("NghienCuuKhoaHoc.Data.Models.Department", "Department")
                        .WithMany("Personals")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.Research", b =>
                {
                    b.HasOne("NghienCuuKhoaHoc.Data.Models.Personal", "Personal")
                        .WithMany("Researches")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.ResearchAcceptance", b =>
                {
                    b.HasOne("NghienCuuKhoaHoc.Data.Models.Research", "Research")
                        .WithOne("ResearchAcceptance")
                        .HasForeignKey("NghienCuuKhoaHoc.Data.Models.ResearchAcceptance", "ResearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Research");
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.ResearchFile", b =>
                {
                    b.HasOne("NghienCuuKhoaHoc.Data.Models.Research", "Research")
                        .WithMany("ResearchFiles")
                        .HasForeignKey("ResearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Research");
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.Department", b =>
                {
                    b.Navigation("Personals");
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.Personal", b =>
                {
                    b.Navigation("CouncilMembers");

                    b.Navigation("Researches");
                });

            modelBuilder.Entity("NghienCuuKhoaHoc.Data.Models.Research", b =>
                {
                    b.Navigation("CouncilMembers");

                    b.Navigation("ResearchAcceptance")
                        .IsRequired();

                    b.Navigation("ResearchFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
